---
# Add necessary apt repositories before installing packages
- name: Add universe repository
  become: true
  apt_repository: 
    repo: 'deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe'
    state: present 
  # This task causes an update_cache that results in warnings that are interpreted as errors, possibly due to adding the certbot PPA
  # See https://github.com/ansible/ansible/issues/30754

- name: Add certbot repository
  become: true
  apt_repository: 
    repo: 'ppa:certbot/certbot'
    state: present

# Update and Install required apt packages
- name: Install prod dependencies
  become: true
  apt:
    name: "{{ item }}"
    update: true
    update_cache: true
    state: present
  with_items:
    - 'git'
    - 'pipenv'
    - 'nginx'
    - 'software-properties-common'
    - 'certbot'
    - 'python-certbot-nginx'
  shell: "python"
    
- name: Create project directory
  file:
    path: "{{ frontend_project_path }}"
    state: directory
    owner: "{{ frontend_user_name }}"
    mode: 0755

- name: Checkout repo
  git:
    accept_hostkey: true
    force: true
    update: true
    repo: "{{ frontend_git_repo }}"
    dest: "{{ frontend_project_path }}"
    version: "{{ frontend_git_branch }}"

# Source: https://github.com/pypa/pipenv/issues/363#issuecomment-421310544
- name: Check for venv
  ignore_errors: true
  command: "pipenv --venv"
  args:
    chdir: "{{ frontend_project_path }}"
  register: pipenv_venv_check_cmd
  changed_when:
    - ('No virtualenv' not in pipenv_venv_check_cmd.stderr)

- name: Run pipenv install
  command: "pipenv install"
  args:
    chdir: "{{ project_root }}"
  when:
    - ('No virtualenv' in pipenv_venv_check_cmd.stderr) 

# There is a UFW module added to Ansible as of v 1.6, see here: https://docs.ansible.com/ansible/2.4/ufw_module.html
- name: Enable UFW
  ufw: 
    state: enabled
    policy: disallow # By default, we disallow all connections other than those we specifically allow
    
- name: UFW logging on
  ufw:
    logging: on
    
- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH
    
- name: Allow Nginx
  ufw:
    rule: allow
    name: Nginx

- name: Allow port 80 tcp
  ufw:
    rule: allow
    port: 80
    proto: tcp
    
- name: Allow port 443 tcp
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Copy Nginx config
  become: true
  copy:
    src: cce-search.conf
    dest: /etc/nginx/conf.d/cce-search,conf
    owner: "{{ frontend_user_name }}"
    group: "{{ frontend_user_name }}"
    mode: 0755
  
# Both start Nginx and enable it to restart on reboot
- name: Enable Nginx
  become: true
  raw: 'systemctl nginx start && systemctl nginx enable'

# Configure HTTPS cert w/ Certbot
- name: Generate HTTPS cert
  become: true
  command: "certbot --nginx" # Does this command halt for [y/n] input?

# TODO: Run app